# Generated by Django 6.0.5 on 2026-06-06 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-sermon_date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='sermon_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
