# Generated by Django 6.0.5 on 2026-06-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_options_alter_sermon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
