# Generated by Django 6.0.5 on 2026-06-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_alter_websiteconfiguration_hero_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
