# Generated by Django 6.0.5 on 2026-09-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ministrybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization/Church'), ('business', 'Business'), ('prayer', 'Prayer Partner'), ('financial', 'Financial Partner'), ('volunteer', 'Volunteer Partner'), ('building', 'Building Project')], max_length=20),
        ),
    ]
