# Generated by Django 6.0.5 on 2026-09-21 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_partner_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('request', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('prayed_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sermon',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(),
        ),
    ]
