# Generated by Django 6.0.5 on 2026-09-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prayerwall_sermon_date_alter_sermon_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='partner',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
