# Generated by Django 6.0.5 on 2026-09-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
