# Generated by Django 6.0.5 on 2026-09-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_onlinetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorshipAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='worship/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='onlinetracker',
            name='ip_address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='onlinetracker',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
